.\" Process this file with
.\" groff -man -Tascii exadrums.1
.\"
.TH EXADRUMS 1 "2020-05-09" eXaDrums "eXaDrums Manual Pages"
.SH NAME
eXaDrums \- Software drum module.
.SH SYNOPSIS
.B exadrums [options] 
.B ...
.SH DESCRIPTION
Exadrums communicates with libexadrums to provide most features of a modern drum module.
The program can also be used in cli mode, in which case it provides several options.
.SH OPTIONS
eXaDrums accepts the following options:
.TP 8
.B \-v, \-\-version
Show eXaDrums command\-line options.
.TP 8
.B \-r, \-\-reset\-config
Reset to default configuration.
.TP 8
.B \-c, \-\-config \fI<directory>\fP
Set cofiguration directory.
.TP 8
.B \-i, \-\-import\-config \fI<file>\fP
Import configuration from file.
.TP 8
.B \-e, \-\-export\-config \fI<directory>\fP
Export configuration to directory.
.TP 8
.B \-f, \-\-fullscreen
Start in fullscreen mode.
.SH BUGS
Please contact the author if you find a bug.
.SH AUTHOR
Jeremy Oden
