.\" Process this file with
.\" groff -man -Tascii exadrums.1
.\"
.TH EXADRUMS 1 "2018-06-28" eXaDrums "User Manuals"
.SH NAME
eXaDrums \- Drum module for Linux.
.SH SYNOPSIS
.B exadrums [options] 
.B ...
.SH DESCRIPTION
A drum module with a nice and modern user interface.
Exadrums communicates with libexadrums to provide most features of a modern drum module.
The program can also be used in cli mode, in which case it provides several options.
.SH OPTIONS
.B 
.IP "-v"
Prints the version that is currently installed.
.SH BUGS
Please contact the author if you find a bug.
.SH AUTHOR
Jeremy Oden
