Document: exadrums
Title: Debian exadrums Manual
Author: <insert document author here>
Abstract: This manual describes what exadrums is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/exadrums/exadrums.sgml.gz

Format: postscript
Files: /usr/share/doc/exadrums/exadrums.ps.gz

Format: text
Files: /usr/share/doc/exadrums/exadrums.text.gz

Format: HTML
Index: /usr/share/doc/exadrums/html/index.html
Files: /usr/share/doc/exadrums/html/*.html
